title: <p align="center"> Lydia Nguyen </p>

logo: "profile-round.png?raw=true" 

description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/lydia-nguyen-1a6b2484/">LinkedIn</a> |
  <a href="https://github.com/n-lydia">GitHub</a>
  </p>
  
theme: jekyll-theme-minimal
